version: '3.8'

services:
  api:
    image: ghcr.io/kaneo-app/api:latest
    environment:
      - JWT_ACCESS=jwt_secret_goes_here
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    restart: unless-stopped

  web:
    image: ghcr.io/kaneo-app/web:latest
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped