services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: ghcr.io/kaneo-app/api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      JWT_ACCESS: "change_me"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - .:/app

  frontend:
    image: ghcr.io/kaneo-app/web:latest
    environment:
      KANEO_API_URL: "https://demo-api.kaneo.app"
    ports:
      - 80:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - backend
    restart: unless-stopped
