version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - JWT_ACCESS=jwt_secret_goes_here
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped