name: Generate Changelog and Create Patch Version
on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Bump version and generate changelog (patch)
        run: npx standard-version --release-as patch

      - name: Push changes
        run: |
          git push --follow-tags origin main