name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
