name: Docker Build, Changelog, and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push web Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: ./apps/web/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/web:latest
            ghcr.io/${{ github.repository_owner }}/web:${{ github.sha }}

      - name: Build and push api Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: ./apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api:latest
            ghcr.io/${{ github.repository_owner }}/api:${{ github.sha }}