name: Docker Build, Changelog, and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: List files in apps/web
        run: ls -l apps/web

      - name: Build and push web Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/web:latest
            ghcr.io/${{ github.repository_owner }}/web:${{ github.sha }}

      - name: Build and push api Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api:latest
            ghcr.io/${{ github.repository_owner }}/api:${{ github.sha }}